name: Majsoul-Login
on:
  workflow_dispatch:
  schedule: #5:00
   - cron: '0 21 * * *'
jobs:
  login:
    name: Majsoul-Login
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Selenium
        run: pip install selenium==4.17.2

      - name: Majsoul login
        run: python login.py ${{ secrets.EMAIL }} ${{ secrets.PASSWD }}

      - name: Check log file  
        run: |  
          ls  
          if [ -f "log.txt" ]; then  
            cat log.txt  
          else  
            echo "log.txt not found!"  
          fi  
      - name: git config
        run: |-
         git config --global user.name "Github Actions"
         git config --global user.email "actions@gmail.com"
         
      - name: Push
        run: |-
          git diff
          git status
          git add -A
          git commit -m "update by github actions"
          git push
